language: python
python:
- '2.7'
script:
- PYTHONPATH=`pwd` python tests/test_api.py
deploy:
  provider: pypi
  user: lensonp
  password:
    secure: SNzJCTgg+0w1xuM3UOj+jD7mooa9IxfKIFfRgtUV2Kr2UmzMbHoDR2te5GjAsaTH/+B620swRfGXkwoFbw+Pa0fYuCqmKHqcGdhGbj9pGcrInq7Ga5p+FawUx7wBZi11yaRTt9zfwC8eP4N1ACSjEC2c1btzpmBplia1qFsTO6cgB9POJ4otcH7v0y1nmplD66eln8pkyM2tPNEjxESO6sHnGBoIxvrMG2gEPj37G6hzzhTvtT52gaIQ9/30pqBXVHTrFgTJistj0mplvX0Vzcpl8Gk5xMFziJ3Tzjic5rxfFE9Zoj4SRPnJvBVF5VpTvT0RYYgVdXuPQ5YYtwsVxjKQJeTE6bgvbXiLo0s1khuGZA9RqPkZumQhb/ezUDaTbXbLnOAy03ccYip+/fllPvKwkjo60CmeYFOuTchkbjHZHtzqjse719Zl+Xp1NUs3ZwEi/P5hpFGFJsjPB75o08N5VpviE6cKeDIUbYUzDApHAfqWq8H5YLy3DpC7olHxDrlHOaHsucLhwwUStIe4Yrz6NeMHk4zn5sHKVj0/QYy829YN2oNpVKXqIuBA1w+NuPKmIz1/v4MV1fARkwRgTvVQsCImThKFWMI2yWqJqsT0vp7X+AbxKRoRZ1bixiGLdMWMo1y7ZW3irb6orGorCmnMWYHzQ2mKGnxVlhzglJk=
  on:
    tags: true
  distributions: sdist bdist_wheel
